import type { Metadata } from "next";
import { Outfit, Ovo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const outfit = Outfit({
  subsets: ["latin"], weight: ["400", "500", "600", "700"],
  variable: '--font-outfit', // 🚀 Define variable
});

const ovo = Ovo({
  subsets: ["latin"], weight : ["400"],
  variable: '--font-ovo', // 🚀 Define variable
});

export const metadata: Metadata = {
  title: "Stargirl Strategy | Social media management",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${ovo.variable} ${outfit.className} antialiased`}
      >
        <Navbar />
        <main className="min-h-screen">
            {children}
        </main>
       <Footer />
      </body>
    </html>
  );
}
